map_server:
  ros__parameters:
    qos_overrides:
      /map:
        reliability: reliable      # 持续发布，确保订阅方不会丢失数据
        durability: transient_local # 保留最后一条消息，供后启动的节点（如 RViz）获取
        
controller_server:
  ros__parameters:
    global_frame: odom  
    robot_base_frame: base_link
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      # 运动参数
      max_vel_x: 0.5
      min_vel_x: 0.1
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      acc_lim_x: 1.0
      acc_lim_theta: 0.6
      xy_goal_tolerance: 0.30
      yaw_goal_tolerance: 0.05
      holonomic_robot: false 
      # 确保指定成本地图话题
      costmap_topic: local_costmap/costmap_raw
      footprint_topic: local_costmap/published_footprint
      # DWA特有参数
      sim_time: 2.0
      vx_samples: 30
      vtheta_samples: 40
      resolution: 0.05
      # 必须添加的目标检查器配置
      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.30
        yaw_goal_tolerance: 0.05
      # 添加传感器配置
      observation_sources: scan
      scan:
        topic: /scan
        data_type: "LaserScan"
        marking: true
        clearing: true

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: true
      allow_unknown: true
      tolerance: 0.5
      # 添加代价转换函数
      cost_travel_factor: 1.0
      use_final_approach_orientation: false

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link 
      update_frequency: 1.0
      publish_frequency: 1.0
      static_map: true
      rolling_window: false
      # 插件声明
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        # topic: /scan
        observation_sources: scan
        scan:
          topic: /scan
          data_type: LaserScan
          marking: true
          clearing: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.2
        cost_scaling_factor: 8.0
      track_unknown_space: true
      always_send_full_costmap: true

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom  
      robot_base_frame: base_link
      update_frequency: 10.0
      publish_frequency: 10.0
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      # 插件声明
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        # topic: /scan
        observation_sources: scan
        scan:
          topic: /scan
          data_type: LaserScan
          marking: true
          clearing: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.2
        cost_scaling_factor: 4.0
      track_unknown_space: true
      rolling_window: true
      always_send_full_costmap: true 

# 通用传感器配置
costmap_common:
  ros__parameters:
    robot_radius: 0.12
    transform_tolerance: 0.5
    obstacle_range: 5.0
    raytrace_range: 5.5
    inflation_radius: 0.2
    # 传感器配置
    observation_sources: scan
    scan:
      sensor_frame: base_link
      data_type: "LaserScan"
      topic: "/scan"
      marking: true
      clearing: true
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0

amcl:
  ros__parameters:
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    use_sim_time: true  
    update_min_d: 0.1  
    update_min_a: 0.05  

# 生命周期管理器配置
lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names: 
      - map_server
      - amcl
      - planner_server
      - controller_server
      - smoother_server
      - behavior_server
      - bt_navigator
    bond_timeout: 10.0
    bringup_order: [map_server, amcl, planner_server, controller_server]